"""
Render docs/validation/table3_theorem1.json as LaTeX tables (docs/validation/table3.tex), so the paper
tables are generated from the results file, not typed by hand.

    python scripts/render_table3.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE = REPO_ROOT / "docs" / "validation" / "table3_theorem1.json"
TARGET = REPO_ROOT / "docs" / "validation" / "table3.tex"


def pct(x: float, digits: int = 2) -> str:
    return f"{100 * x:.{digits}f}\\%"


def render(report: dict) -> str:
    setting = report["setting"]
    parts = [
        "% Generated by scripts/render_table3.py from docs/validation/table3_theorem1.json. Do not edit by hand.",
        f"% SIMULATED (full bb84_numpy protocol): n = {setting['n_qubits']}, sample fraction = "
        f"{setting['sample_fraction']}, {setting['trials']} trials x {setting['links']} links per row, "
        f"seed {setting['seed']}.",
    ]
    for e in sorted({c["bit_flip"] for c in report["table3"]}):
        rows = [c for c in report["table3"] if c["bit_flip"] == e]
        parts += [
            "",
            "\\begin{table}[t]",
            "\\centering",
            f"\\caption{{BB84 QBER validation, \\emph{{simulated}} ($n={setting['n_qubits']}$, sample fraction "
            f"${setting['sample_fraction']}$, bit-flip noise $e={100 * e:g}\\%$, {setting['trials']} trials "
            f"$\\times$ {setting['links']} links per $\\alpha$). Mean $\\pm$ 95\\% CI of the sampled QBER "
            f"estimate; state shares are per link; the last column is the system (max over "
            f"{setting['links']} links).}}",
            "\\begin{tabular}{rrrrrr}",
            "\\hline",
            "$\\alpha$ & Theory & Mean $\\pm$ CI & Std & Secure / Caution / Lockdown & System lockdown \\\\",
            "\\hline",
        ]
        for c in rows:
            s = c["link_state_shares"]
            parts.append(
                f"{c['alpha']:.2f} & {pct(c['theoretical_qber'])} & {pct(c['estimate_mean'])} "
                f"$\\pm$ {pct(c['estimate_mean_ci95_half_width'])} & {pct(c['estimate_std'])} & "
                f"{100 * s['SECURE']:.1f} / {100 * s['CAUTION']:.1f} / {100 * s['LOCKDOWN']:.1f}\\% & "
                f"{pct(c['system_p_lockdown_simulated'], 1)} \\\\"
            )
        parts += ["\\hline", "\\end{tabular}", "\\end{table}"]
    return "\n".join(parts) + "\n"


def main() -> int:
    report = json.loads(SOURCE.read_text(encoding="utf-8"))
    TARGET.write_text(render(report), encoding="utf-8")
    print(f"Wrote {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
